Autopark Web Version/Models/Models/Details.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Autopark_Web_Version.Models
{
    public class Details
    {
        public int DetailId { get; set; }
        public string DetailName { get; set; }
    }
}

Autopark Web Version/Models/Models/OrderDetails.cs
using System;
using Autopark_Web_Version.Models.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Autopark_Web_Version.Models.Models
{
    public class OrderDetails
    {
        public int OrderDetailId { get; set; }
        public int OrderId { get; set; }
        public int VenicleId { get; set; }
        public int Quantity { get; set; }
        public int DetailId { get; set; }
        public virtual Venicles Venicles { get; set; }
        public virtual VenicleType VenicleType { get; set; }
        public virtual Details Details { get; set; }
    }
}

Autopark Web Version/Controllers/DetailsController.cs
using Autopark_Web_Version.Models;
using Autopark_Web_Version.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Autopark_Web_Version.Controllers
{
    public class DetailsController : Controller
    {
        readonly IDetailsRepository<Details> details;        
        public DetailsController(IDetailsRepository<Details> details)
        {
            this.details = details;            
        }

        public async Task<ActionResult> Index()
        {      
            return View(await details.GetAll());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Details newDetail)
        {
            await details.Create(newDetail);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(int id)
        {
            var currentDetail = await details.Get(id);
            if (currentDetail != null)
                return View(currentDetail);
            return NotFound();
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Details editedDetail)
        {
            await details.Update(editedDetail);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<ActionResult> ConfirmDelete(int id)
        {
            var deletingDetail = await details.Get(id);
            if (deletingDetail != null)
                return View(deletingDetail);
            return NotFound();
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            await details.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]        
        public async Task<ActionResult> Details(int id)
        {
            var currentDetail = await details.Get(id);            
            if (currentDetail != null)
                return View(currentDetail);
            return NotFound();
        }
    }
}

Autopark Web Version/Controllers/OrderDetailsController.cs
using Autopark_Web_Version.Models;
using Autopark_Web_Version.Models.Interfaces;
using Autopark_Web_Version.Models.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Autopark_Web_Version.Controllers
{
    public class OrderDetailsController : Controller
    {
        readonly IOrderDetailsRepository<OrderDetails> orderDetails;
        readonly IDetailsRepository<Details> details;
        readonly IOrdersRepository<Orders> orders;
        public OrderDetailsController(IOrderDetailsRepository<OrderDetails> orderDetails, IDetailsRepository<Details> details, IOrdersRepository<Orders> orders)
        {
            this.orderDetails = orderDetails;            
            this.details = details;
            this.orders = orders;
        }        

        public async Task<ActionResult> Create(int id)
        {
            ViewBag.Details = await details.GetAll();
            ViewBag.Order = await orders.Get(id);
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(OrderDetails newOrder)
        {
            await orderDetails.Create(newOrder);
            return Redirect("/Orders/Index");
        }

        [HttpGet]        
        public async Task<ActionResult> Details(int id)
        {
            ViewBag.Details = await details.GetAll();
            var currentOrderDetails = await orderDetails.GetAllByOrderId(id);
            if (orderDetails != null)
                return View(currentOrderDetails);
            return NotFound();
        }
    }
}

Autopark Web Version/Controllers/OrdersController.cs
using Autopark_Web_Version.Models.Models;
using Microsoft.AspNetCore.Mvc;
using Autopark_Web_Version.Models.Interfaces;
using Autopark_Web_Version.Models;
using System.Threading.Tasks;

namespace Autopark_Web_Version.Controllers
{
    public class OrdersController : Controller
    {
        readonly IVOrdersRepository<VOrders> ordersView;
        readonly IOrdersRepository<Orders> orders;
        readonly IVenicleRepository<Venicles> venicles;
        public OrdersController(IVOrdersRepository<VOrders> ordersView, IOrdersRepository<Orders> orders, IVenicleRepository<Venicles> venicles)
        {
            this.ordersView = ordersView;
            this.orders = orders;
            this.venicles = venicles;
        }
        public async Task<ActionResult> Index()
        {
            return View(await ordersView.GetAll());
        }

        public async Task<ActionResult> Create()
        {
            ViewBag.Venicles = await venicles.GetAll();
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Orders newOrder)
        {
            await orders.Create(newOrder);
            return RedirectToAction("Index");
        }
    }
}

Autopark Web Version/Views/OrderDetails/Create.cshtml
@model Autopark_Web_Version.Models.Models.OrderDetails

@{
    ViewData["Title"] = "New Order";
}
<h2>@ViewData["Title"]</h2>

<form asp-action="Create" asp-controller="OrderDetails">
    <div>        
        <div class="form-group">            
            <input type="hidden" asp-for="OrderId" value=@ViewBag.Order.OrderId class="form-control  form-control-sm" />
        </div>
        <div class="form-group">           
            <input type="hidden" asp-for="VenicleId" value=@ViewBag.Order.VenicleId class="form-control  form-control-sm" />
        </div>
        <div class="form-group">
            <label asp-for="DetailId"></label>
            <select class="form-control" asp-for="DetailId">
                @foreach (var item in ViewBag.Details)
                {
                    <option value=@item.DetailId>@item.DetailName</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label asp-for="Quantity"></label>
            <input asp-for="Quantity" class="form-control  form-control-sm" />
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-outline-secondary" />
        </div>
    </div>
</form>

<div>
    <a asp-controller="Orders" asp-action="Index">Back</a>
</div>

Autopark Web Version/Views/OrderDetails/Details.cshtml
@model IEnumerable<Autopark_Web_Version.Models.Models.OrderDetails>
@{
    ViewData["Title"] = "Order Details";
}
<table class="table table-sm">
    <thead>
        <tr>
            <th scope="col">Detail Name</th>
            <th scope="col">Quantity</th>
        </tr>
    </thead>
    <tbody>        
        @foreach (var item in Model)
        {
            <tr>
                <th>
                    @foreach (var details in @ViewBag.Details)
                    {
                        if (details.DetailId == @item.DetailId)
                        {
                            @details.DetailName;
                        }
                    }                    
                </th>

                <th>
                    @item.Quantity
                </th>
            </tr>

        }
    </tbody>
</table>
<div> 

    <div>
        <a asp-controller="Orders" asp-action="Index">Back</a>
    </div>
</div>